version: '3.2'

services:

  db:
    image: viderum/ckan-cloud-docker:db-latest
    build:
      context: db
    restart: always
    ports:
    - "5432:5432"
    env_file:
    - docker-compose/db-secrets.sh
    volumes:
    - db:/var/lib/postgresql/data
    networks:
    - ckan-multi

  jobs-db:
    image: postgres
    restart: always
    ports:
    - "5433:5432"
    env_file:
    - docker-compose/db-secrets.sh
    volumes:
    - jobs-db:/var/lib/postgresql/data
    networks:
    - ckan-multi

  datastore-db:
    image: viderum/ckan-cloud-docker:db-latest
    restart: always
    ports:
    - "5434:5432"
    env_file:
    - docker-compose/datastore-db-secrets.sh
    volumes:
    - datastore-db:/var/lib/postgresql/data
    networks:
    - ckan-multi

  ckan:
    depends_on:
    - db
    - jobs-db
    - datastore-db

volumes:
  db:
  jobs-db:
  datastore-db:
