version: '3.2'

services:

  nginx:
    ports:
    - "8080:8080"

  ckan:
    image: viderum/ckan-cloud-docker:ckan-latest-gdx-demo-theme
    ports:
    - "5000:5000"
    build:
      args:
        EXTRA_PACKAGES: curl
        EXTRA_FILESYSTEM: "./overrides/gdx-demo/filesystem/"
        POST_INSTALL: |
          install_standard_ckan_extension_github -r datopian/ckanext-authz-service &&\
          install_standard_ckan_extension_github -r datopian/ckanext-external-storage -b implement-resource-upload-flow
        POST_DOCKER_BUILD: |
          mkdir -p /var/tmp/ckan/dynamic_menu &&\
          mkdir -p /var/log/ckan/std/
        CKAN_INIT: |
          cp /var/lib/ckan/main.css /usr/lib/ckan/venv/src/ckan/ckan/public/base/css/main.min.css || true
        ROOT_INIT: |
          curl -sL https://deb.nodesource.com/setup_13.x | bash - && apt-get install nodejs && npm version &&\
          cd /usr/lib/ckan/venv/src/ckanext-external-storage &&\
          npm install && npm run build && cd -
    environment:
    - CKAN_CONFIG_TEMPLATE_PREFIX=gdx-demo-theme-
  jobs:
    image: viderum/ckan-cloud-docker:ckan-latest-gdx-demo-theme
    environment:
    - CKAN_CONFIG_TEMPLATE_PREFIX=gdx-demo-theme-

  db:
    image: mdillon/postgis
    build:
      args:
        DB_INIT: |
          psql --dbname="ckan" -c "CREATE EXTENSION IF NOT EXISTS postgis;                  \
                                   CREATE EXTENSION IF NOT EXISTS postgis_topology;         \
                                   CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;            \
                                   CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;"
