version: '3.2'

services:

  proxy:
    ports:
      - "80:80"
      - "443:443"

  nginx:
    depends_on:
      - proxy
      - varnish

  ckan:
    image: viderum/ckan-cloud-docker:ckan-latest-vital-strategies-theme
    build:
      context: ckan
      args:
        POST_INSTALL: |
          install_standard_ckan_extension_github TkTech/ckanext-cloudstorage ckanext-cloudstorage &&\
          install_standard_ckan_extension_github okfn/ckanext-sentry ckanext-sentry &&\
          install_standard_ckan_extension_github ViderumGlobal/ckanext-querytool ckanext-querytool &&\
          install_standard_ckan_extension_github ckan/ckanext-geoview ckanext-geoview
    environment:
      - CKAN_CONFIG_TEMPLATE_PREFIX=vital-strategies-theme-

  jobs:
    image: viderum/ckan-cloud-docker:ckan-latest-vital-strategies-theme
    build:
      context: ckan
      args:
        POST_INSTALL: |
          install_standard_ckan_extension_github TkTech/ckanext-cloudstorage ckanext-cloudstorage &&\
          install_standard_ckan_extension_github ViderumGlobal/ckanext-querytool ckanext-querytool &&\
          install_standard_ckan_extension_github ckan/ckanext-geoview ckanext-geoview
    environment:
      - CKAN_CONFIG_TEMPLATE_PREFIX=vital-strategies-theme-

  db:
    image: mdillon/postgis
    build:
      args:
        DB_INIT: |
          psql --dbname="ckan" -c "CREATE EXTENSION IF NOT EXISTS postgis;                  \
                                   CREATE EXTENSION IF NOT EXISTS postgis_topology;         \
                                   CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;            \
                                   CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;"
