version: '3.2'

services:

  proxy:
    image: traefik:1.7.2-alpine
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
      - "8081:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - $PWD/../traefik/vital-strategies.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:monitor.vital-strategies.l3.ckan.io
      - traefik.port=8080 
    networks:
    - ckan-multi

  ckan:
    image: viderum/ckan-cloud-docker:ckan-latest-vital-strategies-theme
    depends_on:
      - proxy
    build:
      context: ckan
      args:
        POST_INSTALL: |
          install_standard_ckan_extension_github keitaroinc/ckanext-s3filestore ckanext-s3filestore &&\
          install_standard_ckan_extension_github okfn/ckanext-sentry ckanext-sentry &&\
          install_standard_ckan_extension_github ViderumGlobal/ckanext-querytool ckanext-querytool &&\
          install_standard_ckan_extension_github ckan/ckanext-geoview ckanext-geoview
    environment:
      - CKAN_CONFIG_TEMPLATE_PREFIX=vital-strategies-theme-

  nginx:
    labels:
      - traefik.backend=nginx
      - traefik.frontend.rule=Host:nginx.vital-strategies.l3.ckan.io
      - traefik.docker.network=ckan-multi
      - traefik.port=80

  jobs:
    image: viderum/ckan-cloud-docker:ckan-latest-vital-strategies-theme
    labels:
      - traefik.enable=false
    build:
      context: ckan
      args:
        POST_INSTALL: |
          install_standard_ckan_extension_github keitaroinc/ckanext-s3filestore ckanext-s3filestore &&\
          install_standard_ckan_extension_github ViderumGlobal/ckanext-querytool ckanext-querytool &&\
          install_standard_ckan_extension_github ckan/ckanext-geoview ckanext-geoview
    environment:
      - CKAN_CONFIG_TEMPLATE_PREFIX=vital-strategies-theme-

  db:
    image: mdillon/postgis
    labels:
      - traefik.enable=false
    build:
      args:
        DB_INIT: |
          psql --dbname="ckan" -c "CREATE EXTENSION IF NOT EXISTS postgis;                  \
                                   CREATE EXTENSION IF NOT EXISTS postgis_topology;         \
                                   CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;            \
                                   CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;"
