defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$58JDjueE$PN1AKx.4vtLrVvUK5X6DA0"]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[api]
entrypoint="dashboard"

[vital-strategies]
email = "your_email@your_domain"
storage = "vital-strategies.json"
entryPoint = "https"
onHostRule = true
  [vital-strategies.httpChallenge]
  entryPoint = "http"

[docker]
domain = "vital-strategies.l3.ckan.io"
watch = true
network = "web"